### ISSUE TITLE
Importing `JsValue` in a `proc_macro` causes a compilation error on recent nightly's

### ISSUE THREAD

**Issue by finnbear** [futursolo/stylist-rs#120] opened 2023-05-24 05:02 UTC
Thanks for the crate! I noticed a regression on recent Rust nightly's that causes a linker error when using stylist.

- Rust regression issue: https://github.com/rust-lang/rust/issues/111888

- `JsValue` inclusion: https://github.com/futursolo/stylist-rs/blob/fbd788f0a9a63ccadf6a25e028829a25224140eb/packages/stylist-core/src/error.rs#L19
(this type is later imported by `stylist-macros` but, as far as I know, this variant won't be constructed there)

*I'll work on a PR to see if `JsValue` can be removed for `proc_macro` purposes.*

**Comment by futursolo** [comment] 2023-05-24 05:10
Is this a duplicate of #114?

**Comment by finnbear** [comment] 2023-05-24 05:18
> Is this a duplicate of #114?

Almost certainly yes!

**Comment by futursolo** [comment] 2023-06-11 09:29
I have submitted a [pull request](https://github.com/futursolo/stylist-rs/pull/123) awaiting code review from @WorldSEnder.

Until this is mitigated from stylist, there is a [comment](https://github.com/rust-lang/rust/issues/111888#issuecomment-1567421827) in the compiler regression issue about how to mitigate the impact by switching the linker to lld until Rust compiler is fixed.

**Comment by vaassi** [comment] 2023-06-11 09:43
solution with lld doesn't work for me but adding this in Cargo.toml with rust 1.70 helps me to solve this issue

[profile.dev.package.wasm-bindgen]
debug-assertions = false

**Comment by rambip** [comment] 2023-06-24 14:55
Same error here, I can't compile stylist.
Im on rust 1.70

**Comment by rambip** [comment] 2023-06-24 15:06
After going back to rust 1.69, I can confirm that it is a version issue (it worked with 1.69)

**Closed** 2023-06-25 15:01 UTC

**Comment by futursolo** [comment] 2023-06-25 15:56
Stylist v0.12.1 has been released, which should also mitigate this issue from within stylist.
Affected users can run `cargo update` in their projects and it should pick up the new version automatically.

**Comment by futursolo** [comment] 2023-09-16 10:59
This current workaround has a couple requirements:

1. For single crate applications, you need to use edition 2021.
2. For applications inside a workspace, you need to enable cargo resolver 2. (See #129)

In addition, since Rust 1.72 has fixed this regression and this workaround is no longer needed, I do plan to remove the workaround.

The current plan is once 1.72 has been released for 6 months, we bump the MSRV requirement to 1.72 to avoid this regression and remove the workaround.
