### ISSUE TITLE
v0.13.0 the trait bound `stylist::StyleSource: std::convert::From<&str>` is not satisfied

### ISSUE THREAD

**Issue by einsli** [futursolo/stylist-rs#153] opened 2023-12-23 16:00 UTC
I follow the example as bellow

```rust
use stylist::Style;

let style_str = r#"
background-color: red;

.nested {
    background-color: blue;
    width: 100px
}
"#;

let style = Style::new(style_str).expect("Failed to create style");
```

the error is the trait bound `stylist::StyleSource: std::convert::From<&str>` is not satisfied
the trait `std::convert::From<stylist::ast::Sheet>` is implemented for `stylist::StyleSource`
required for `&str` to implement 

here is the Cargo.toml 
```toml
[dependencies]
stylist = {version="0.13.0",features=["yew","yew_use_style"]}
yew = { version = "0.21.0", features = ["csr"] }
```

**Comment by WorldSEnder** [comment] 2023-12-26 16:13
Enable the [`parser`](https://docs.rs/stylist/latest/stylist/#features-flags) feature.

**Comment by WorldSEnder** [comment] 2023-12-26 16:18
Duplicate of #152

**Closed by WorldSEnder** 2023-12-26 16:18 UTC
