### ISSUE TITLE
Compiling stylist-macros v0.12.0 error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by vaassi** [futursolo/stylist-rs#125] opened 2023-06-11 08:35 UTC
Try to use stylist in Cargo.toml
stylist = { version = "0.12", features = ["yew_integration"] }

get error during cargo build phase

**#rustup check**
stable-x86_64-unknown-linux-gnu - Up to date : 1.70.0 (90c541806 2023-05-31)

Compiling stylist-macros v0.12.0
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/user/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/15/bin:/opt/vmware/bin:/opt/vmware/sbin:/home/user/.local/bin:/home/user/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcQYrzo2/list" "-Wl,--no-undefined-version" "-m64" "/tmp/rustcQYrzo2/symbols.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.0.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.1.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.10.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.11.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.12.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.13.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.14.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.15.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.2.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.3.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.4.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.5.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.6.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.7.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.8.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.stylist_macros.030b8c2b-cgu.9.rcgu.o" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.soc2pawcesgnzrk.rcgu.rmeta" "/home/user/projects/ab/target/debug/deps/stylist_macros-b7f74decd83cf90b.360gij5e1y389xcq.rcgu.o" "-Wl,--as-needed" "-L" "/home/user/projects/ab/target/debug/deps" "-L" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/user/projects/ab/target/debug/deps/libstylist_core-46925b523ab7ce53.rlib" "/home/user/projects/ab/target/debug/deps/libwasm_bindgen-350ae4a473d57feb.rlib" "/home/user/projects/ab/target/debug/deps/libcfg_if-3f62c4595cfb0baa.rlib" "/home/user/projects/ab/target/debug/deps/libnom-fcba2d9d7a99a38c.rlib" "/home/user/projects/ab/target/debug/deps/libmemchr-e74db8b53b88b925.rlib" "/home/user/projects/ab/target/debug/deps/libonce_cell-a595d82778a3af25.rlib" "/home/user/projects/ab/target/debug/deps/libserde-9b669eef3f5dd4ac.rlib" "/home/user/projects/ab/target/debug/deps/libthiserror-cced868b3649f3a0.rlib" "/home/user/projects/ab/target/debug/deps/liblitrs-b347a0d42088f92d.rlib" "/home/user/projects/ab/target/debug/deps/liblog-45c600b3e894b505.rlib" "/home/user/projects/ab/target/debug/deps/libitertools-9551df67672f603d.rlib" "/home/user/projects/ab/target/debug/deps/libeither-70d947bba1fe7fe9.rlib" "/home/user/projects/ab/target/debug/deps/libproc_macro_error-2174fa4729a799e9.rlib" "/home/user/projects/ab/target/debug/deps/libsyn-2fe267db66b4005f.rlib" "/home/user/projects/ab/target/debug/deps/libquote-0852b4f71efda9ad.rlib" "/home/user/projects/ab/target/debug/deps/libproc_macro2-4982945d7a1d0e2c.rlib" "/home/user/projects/ab/target/debug/deps/libunicode_ident-ef343d798e4a7328.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-1e0c4dcd95dfced1.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8389830094602f5a.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-41c1085b8c701d6f.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-f733fcc57ce38b99.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-6495ec9d4ce4f37d.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-1e3796360cca5b49.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-2e7f329b154436e1.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1e1f5b8a84008aa8.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-cbcb223c64b13cf3.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b40bc72e060a8196.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-1eb33ae9877d3c0f.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-0335d894dd05bed7.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-076a893ead7e7ab5.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-2e924dd85b2e9d95.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7975ffb5e62386c4.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-285425b7cea12024.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-38694d775e998991.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-914eb40be05d8663.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-27094fcca7e14863.rlib" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-919e055b306699ae.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/user/projects/ab/target/debug/deps/libstylist_macros-b7f74decd83cf90b.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: __wbindgen_realloc: undefined version: 
          /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: __wbindgen_malloc: undefined version: 
          /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: __wbindgen_free: undefined version: 
          /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: __wbindgen_exn_store: undefined version: 
          /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: failed to set dynamic section sizes: bad value
          collect2: error: ld returned 1 exit status
          

error: could not compile `stylist-macros` (lib) due to previous error

**Comment by futursolo** [comment] 2023-06-11 09:24
Thank you for creating this issue.

This issue is a duplicate of #120, which is a Rust compiler regression https://github.com/rust-lang/rust/issues/111888.
In the Rust compiler issue, there is a comment about how to mitigate by switching this linker to `lld` until Rust compiler is fixed.

**Closed by futursolo** 2023-06-11 09:24 UTC
